# -- This section was auto generated by ds-pypackage --------------------------------
# -- Path setup --------------------------------------------------------------

import os
import sys
from importlib.metadata import PackageNotFoundError, version as pkg_version

# Add the parent directory to the Python path to enable importing modules from the project
sys.path.insert(0, os.path.abspath("../../src"))

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "autoapi.extension",
    "sphinx.ext.githubpages",
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
]
autoapi_dirs = ["../../src"]

# -- End of auto-generated section ------------------------------------------------
# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "ds-resource-plugin-py-lib"
copyright = "2025, Aider AS"
author = "Kristoffer Varslott"

try:
    version = pkg_version("ds-resource-plugin-py-lib")
except PackageNotFoundError:
    try:
        import tomllib
    except ModuleNotFoundError:  # pragma: no cover
        import tomli as tomllib  # type: ignore[import-not-found]

    with open("../../pyproject.toml", "rb") as f:
        pyproject = tomllib.load(f)
    version = pyproject["project"]["version"]
release = version

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration


templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = "sphinx_material"
html_static_path = ["_static"]
